### PR TITLE
refactoring to style guide

### PR DESCRIPTION
**Pull request by maia**
This PR will (without changing any functionality) adapt many aspects of the [Ruby Style Guide](https://github.com/bbatsov/ruby-style-guide). There still are a few things to do, especially keeping the max line length at not more than ~100 and then refactoring methods into smaller parts. 

Please take a look at the .rubocop configuration and open issues at .rubocop-todo (excluding the disabled tests), I hope it suits your development environment too.

All tests pass.

### CODE REVIEW

**Comment by diasks2** [comment]
Awesome! Thank you! You put a lot of work into that. I really appreciate it. Maybe we should add a few lines to the README describing how to run the rubocop tests and mention that any changes should try to conform to the Ruby Style Guide.

**Comment by maia** [comment]
It wasn't that much work, most of the cops have an `--auto-correct` option. As for adding a note to the readme: I don't consider these styles to be a religious act, and I wouldn't want anyone willing to contribute who's not familiar with rubocop to have to deal with that before committing - everything can be cleaned later too. 

Also I consider these commits as groundwork for other refactorings – I'd like to keep methods short (< 10 lines), with self-explaining names, that's what I'm most worried about (`PostProcessor#post_process`, I'm looking at you). Especially as I'm not very fluent in regex and sometimes it's guesswork to me. :)

**Comment by diasks2** [comment]
Yes, sorry that is very messy. I'll try to break `post_process` down into smaller methods.

**Comment by maia** [comment]
I can offer breaking it up into small parts (one method called per flat_map, and maybe later there's a way to get rid of endless chaining of flat_map), but method names would be unclear (`do_something1`), as I'm clueless what many of these regex do, so you'd have to rename them. :)

**Comment by diasks2** [comment]
I can do that. I think the easy way will be once it is in separate methods to comment out each method one at a time and see what test fails. Then we can easily see what that particular method is doing.

**Pull request merged**
